### ISSUE TITLE
Oh y'a un problème jcrois

### ISSUE THREAD

**Issue by Lemecdegithub** [Parow/flashland-v5#1]
le server se lance etc jvois mon perso spawn puis après j'ai un écran noir avec "chargement du mode de jeu" puis, je suis kick et ça met "Une exception non gérée vient de se produire [GetCharacterLimit], contactez un développeur rapidement."

J'suis censé faire quoi khey ?
![unknown](https://user-images.githubusercontent.com/59922011/72439084-86917580-37a6-11ea-8cc3-99b5d1424445.png)

**Comment by Lemecdegithub** [comment]
+ j'ai bien fais le truc npm i uuid jsais pas quoi dans FXServer\resources\[flashland]\flashland

**Comment by Parow** [comment]
Faut se wl

**Comment by Wolf423** [comment]
Comment fais-ton pour se WL ?
